# This is a generated file. Not intended for manual editing.
services:
  storehouse.api:
    build:
      context: "C:\\Users\\Roflokektikpukpek\\Desktop\\.net learn\\StoreHouseWeb"
      dockerfile: "StoreHouse.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/StoreHouse.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\Roflokektikpukpek\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\Roflokektikpukpek\\.nuget\\packages"
    image: "storehouse.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\Roflokektikpukpek\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Users\\Roflokektikpukpek\\Desktop\\.net learn\\StoreHouseWeb\\StoreHouse.Api:/app:rw"
    - "C:\\Users\\Roflokektikpukpek\\Desktop\\.net learn\\StoreHouseWeb:/src:rw"
    working_dir: "/app"
